### ISSUE TITLE
嗨，非常喜欢你分享的直播源

### ISSUE THREAD

**Issue by hbcxs111** [shangzhouwan/tv#1]
不过有些个别的台已经无法访问了，可以分享一下抓取这些直播源的方法吗？

**Comment by shangzhouwan** [comment]
现在代码在我自己电脑上，等后面有时间整理一下，现在有点乱

**Comment by hbcxs111** [comment]
好的，感谢！

**Comment by shangzhouwan** [comment]
> 好的，感谢！

请关注这个项目：https://github.com/shangzhouwan/iptv
